'use client';

import { useEffect, useMemo, useState } from 'react';
import { SiteHeader } from '@/components/SiteHeader';
import { listListings, type ListingRecord } from '@/lib/api';
import { useAuth } from '@/lib/auth';

function median(values: number[]) { const sorted = [...values].sort((a, b) => a - b); if (!sorted.length) return 0; const middle = Math.floor(sorted.length / 2); return sorted.length % 2 ? sorted[middle] : (sorted[middle - 1] + sorted[middle]) / 2; }
export default function InsightsPage() {
  const { loggedIn, ready } = useAuth(); const [rows, setRows] = useState<ListingRecord[]>([]); const [error, setError] = useState('');
  useEffect(() => { if (loggedIn) listListings().then(x => setRows(x as ListingRecord[])).catch(e => setError(String(e))); }, [loggedIn]);
  const stats = useMemo(() => { const live = rows.filter(x => x.is_live); const locality = new Map<string, number>(); const bhk = new Map<string, number>(); const pps = new Map<string, number[]>(); rows.forEach(x => { const place = x.locality ?? 'unknown'; locality.set(place, (locality.get(place) ?? 0) + 1); if (x.bedroom != null) bhk.set(String(x.bedroom), (bhk.get(String(x.bedroom)) ?? 0) + 1); if (x.price != null && x.carpet_area) { const values = pps.get(place) ?? []; values.push(x.price / x.carpet_area); pps.set(place, values); } }); return { live: live.length, inactive: rows.length - live.length, medianPrice: median(rows.map(x => x.price ?? 0).filter(x => x > 0)), localities: [...locality.entries()].sort((a,b) => b[1]-a[1]).slice(0,8), bhk: [...bhk.entries()].sort((a,b) => Number(a[0])-Number(b[0])), pps: [...pps.entries()].map(([name, values]) => [name, median(values)] as const).sort((a,b) => b[1]-a[1]).slice(0,5) }; }, [rows]);
  if (!ready) return null; return <main className="min-h-screen"><SiteHeader /><section className="mx-auto max-w-7xl px-6 py-10 lg:px-10"><p className="text-sm font-bold uppercase tracking-[.2em] text-[var(--coral)]">Independent read</p><h1 className="mt-2 text-5xl">What the records say.</h1><p className="mt-5 max-w-2xl leading-7 text-[var(--muted)]">The documented analytics endpoint returned 404, so these aggregates are computed from the complete offset-based listings pull.</p>{error && <p className="py-10 text-[var(--coral)]">{error}</p>}<div className="mt-10 grid gap-px bg-[var(--ink)]/10 md:grid-cols-3"><div className="bg-[var(--paper)] p-6"><p className="text-sm text-[var(--muted)]">Median positive price</p><p className="mt-3 text-4xl">₹{stats.medianPrice.toLocaleString('en-IN')}</p></div><div className="bg-[var(--paper)] p-6"><p className="text-sm text-[var(--muted)]">Live records</p><p className="mt-3 text-4xl">{stats.live.toLocaleString('en-IN')}</p></div><div className="bg-[var(--paper)] p-6"><p className="text-sm text-[var(--muted)]">Inactive records</p><p className="mt-3 text-4xl">{stats.inactive.toLocaleString('en-IN')}</p></div></div><div className="mt-12 grid gap-10 md:grid-cols-3"><div><h2 className="text-2xl">Locality volume</h2><ul className="mt-5 space-y-3">{stats.localities.map(([name,count]) => <li key={name} className="flex justify-between border-b border-[var(--ink)]/10 pb-2 text-sm"><span>{name}</span><b>{count}</b></li>)}</ul></div><div><h2 className="text-2xl">Bedrooms</h2><ul className="mt-5 space-y-3">{stats.bhk.map(([name,count]) => <li key={name} className="flex justify-between border-b border-[var(--ink)]/10 pb-2 text-sm"><span>{name} BHK</span><b>{count}</b></li>)}</ul></div><div><h2 className="text-2xl">Price / sq ft</h2><ul className="mt-5 space-y-3">{stats.pps.map(([name,value]) => <li key={name} className="flex justify-between border-b border-[var(--ink)]/10 pb-2 text-sm"><span>{name}</span><b>₹{Math.round(value).toLocaleString('en-IN')}</b></li>)}</ul></div></div></section></main>;
}
