'use client';

import { useEffect, useMemo, useState } from 'react';
import { SiteHeader } from '@/components/SiteHeader';
import { listRentals, type RentalRecord } from '@/lib/api';
import { useAuth } from '@/lib/auth';

export default function RentalsPage() {
  const { loggedIn, ready } = useAuth(); const [rows, setRows] = useState<RentalRecord[]>([]); const [locality, setLocality] = useState(''); const [bedroom, setBedroom] = useState(''); const [page, setPage] = useState(1); const [error, setError] = useState('');
  useEffect(() => { if (loggedIn) listRentals().then(x => setRows(x as RentalRecord[])).catch(e => setError(String(e))); }, [loggedIn]);
  const filtered = useMemo(() => rows.filter(x => (!locality || String(x.locality ?? '').toLowerCase().includes(locality.toLowerCase())) && (!bedroom || x.bedroom === Number(bedroom))), [rows, locality, bedroom]); const visible = filtered.slice((page - 1) * 24, page * 24);
  if (!ready) return null; return <main className="min-h-screen"><SiteHeader /><section className="mx-auto max-w-7xl px-6 py-10 lg:px-10"><p className="text-sm font-bold uppercase tracking-[.2em] text-[var(--coral)]">Monthly rent</p><h1 className="mt-2 text-5xl">Homes to rent.</h1><div className="mt-8 flex flex-wrap gap-3 border-y border-[var(--ink)]/15 py-5"><input placeholder="Locality" value={locality} onChange={e => {setLocality(e.target.value);setPage(1)}} className="border border-[var(--ink)]/15 bg-transparent px-3 py-2" /><select value={bedroom} onChange={e => {setBedroom(e.target.value);setPage(1)}} className="border border-[var(--ink)]/15 bg-transparent px-3 py-2"><option value="">Bedrooms</option>{[1,2,3,4,5].map(n => <option key={n} value={n}>{n} BHK</option>)}</select><span className="self-center text-sm text-[var(--muted)]">{filtered.length} matches</span></div>{error && <p className="py-10 text-[var(--coral)]">{error}</p>}<div className="mt-7 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{visible.map(x => <article key={x.listing_id} className="border border-[var(--ink)]/15 bg-[var(--paper)] p-5"><p className="text-xs uppercase tracking-[.16em] text-[var(--coral)]">{x.furnishing ?? 'rental'}</p><h2 className="mt-7 text-2xl">{x.title ?? x.apartment_name ?? 'Rental home'}</h2><p className="mt-2 text-sm text-[var(--muted)]">{x.locality} · {x.bedroom} BHK · {x.carpet_area} sq ft</p><p className="mt-7 text-xl">₹{Number(x.price ?? 0).toLocaleString('en-IN')} / month</p></article>)}</div><div className="mt-8 flex justify-between border-t border-[var(--ink)]/15 pt-5 text-sm"><button disabled={page === 1} onClick={() => setPage(page - 1)} className="disabled:opacity-30">← Previous</button><span>Page {page} / {Math.max(1, Math.ceil(filtered.length / 24))}</span><button disabled={page * 24 >= filtered.length} onClick={() => setPage(page + 1)} className="disabled:opacity-30">Next →</button></div></section></main>;
}
