'use client';

import { useEffect, useMemo, useState } from 'react';
import { SiteHeader } from '@/components/SiteHeader';
import { listProjects, type ProjectRecord } from '@/lib/api';
import { useAuth } from '@/lib/auth';

export default function ProjectsPage() {
  const { loggedIn, ready } = useAuth(); const [rows, setRows] = useState<ProjectRecord[]>([]); const [locality, setLocality] = useState(''); const [status, setStatus] = useState(''); const [page, setPage] = useState(1); const [error, setError] = useState('');
  useEffect(() => { if (loggedIn) listProjects().then(x => setRows(x as ProjectRecord[])).catch(e => setError(String(e))); }, [loggedIn]);
  const filtered = useMemo(() => rows.filter(x => (!locality || String(x.locality ?? '').toLowerCase().includes(locality.toLowerCase())) && (!status || x.project_status === status)), [rows, locality, status]); const visible = filtered.slice((page - 1) * 24, page * 24);
  if (!ready) return null; return <main className="min-h-screen"><SiteHeader /><section className="mx-auto max-w-7xl px-6 py-10 lg:px-10"><p className="text-sm font-bold uppercase tracking-[.2em] text-[var(--coral)]">Builder projects</p><h1 className="mt-2 text-5xl">Places taking shape.</h1><div className="mt-8 flex flex-wrap gap-3 border-y border-[var(--ink)]/15 py-5"><input placeholder="Locality" value={locality} onChange={e => {setLocality(e.target.value);setPage(1)}} className="border border-[var(--ink)]/15 bg-transparent px-3 py-2" /><select value={status} onChange={e => {setStatus(e.target.value);setPage(1)}} className="border border-[var(--ink)]/15 bg-transparent px-3 py-2"><option value="">Any status</option><option>under construction</option><option>new launch</option><option>ready to move</option></select><span className="self-center text-sm text-[var(--muted)]">{filtered.length} matches</span></div>{error && <p className="py-10 text-[var(--coral)]">{error}</p>}<div className="mt-7 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{visible.map(x => <article key={x.project_id} className="border border-[var(--ink)]/15 bg-[var(--paper)] p-5"><p className="text-xs uppercase tracking-[.16em] text-[var(--coral)]">{x.project_status ?? 'project'}</p><h2 className="mt-7 text-2xl">{x.apartment_name ?? 'Unnamed project'}</h2><p className="mt-2 text-sm text-[var(--muted)]">{x.developer_name} · {x.locality}</p><p className="mt-7 text-xl">₹{Number(x.price_min ?? 0).toLocaleString('en-IN')}–₹{Number(x.price_max ?? 0).toLocaleString('en-IN')}</p><p className="mt-2 text-sm text-[var(--muted)]">{x.total_listings ?? 0} reported listings</p></article>)}</div><div className="mt-8 flex justify-between border-t border-[var(--ink)]/15 pt-5 text-sm"><button disabled={page === 1} onClick={() => setPage(page - 1)} className="disabled:opacity-30">← Previous</button><span>Page {page} / {Math.max(1, Math.ceil(filtered.length / 24))}</span><button disabled={page * 24 >= filtered.length} onClick={() => setPage(page + 1)} className="disabled:opacity-30">Next →</button></div></section></main>;
}
